#!/usr/bin/env python3
"""
VFL Virtual Soccer MVP - Data Loader
Loads league and team data from JSON files

This module provides functionality to load league and team data
from JSON files generated by the data generator.
"""

import json
import os
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)

@dataclass
class Team:
    """Team data structure matching the simulation engine"""
    name: str
    league: str
    country: str
    strength: float
    attack: float
    defense: float
    form: float = 0.0
    home_advantage: float = 0.0
    colors: str = ""
    stadium: str = ""
    capacity: int = 0
    founded: int = 1900
    nickname: str = ""

class DataLoader:
    """
    Loads league and team data from JSON files.
    
    This class provides methods to load data from various JSON file formats
    and convert them into the data structures used by the simulation engine.
    """
    
    def __init__(self, data_dir: str = "data"):
        """
        Initialize the data loader.
        
        Args:
            data_dir (str): Directory containing JSON data files
        """
        self.data_dir = data_dir
        self.leagues: Dict[str, Dict] = {}
        self.teams: Dict[str, Team] = {}
        self.metadata: Dict[str, Any] = {}
    
    def load_client_data(self, client_name: str) -> bool:
        """
        Load complete client data from JSON files.
        
        Args:
            client_name (str): Name of the client
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            client_file = os.path.join(
                self.data_dir, 
                f"{client_name.lower().replace(' ', '_')}_complete.json"
            )
            
            if not os.path.exists(client_file):
                logger.error(f"Client data file not found: {client_file}")
                return False
            
            with open(client_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # Load leagues
            self.leagues = data.get("leagues", {})
            
            # Load teams
            self.teams = {}
            for team_name, team_data in data.get("teams", {}).items():
                self.teams[team_name] = Team(
                    name=team_data["name"],
                    league=team_data["league"],
                    country=team_data["country"],
                    strength=team_data["strength"],
                    attack=team_data["attack"],
                    defense=team_data["defense"],
                    form=team_data.get("form", 0.0),
                    home_advantage=team_data.get("home_advantage", 0.0),
                    colors=team_data.get("colors", ""),
                    stadium=team_data.get("stadium", ""),
                    capacity=team_data.get("capacity", 0),
                    founded=team_data.get("founded", 1900),
                    nickname=team_data.get("nickname", "")
                )
            
            # Load metadata
            self.metadata = data.get("metadata", {})
            
            logger.info(f"✅ Loaded data for {client_name}")
            logger.info(f"📊 Leagues: {len(self.leagues)}")
            logger.info(f"👥 Teams: {len(self.teams)}")
            
            return True
            
        except Exception as e:
            logger.error(f"❌ Error loading client data: {e}")
            return False
    
    def load_league_data(self, league_name: str) -> Optional[Dict]:
        """
        Load data for a specific league.
        
        Args:
            league_name (str): Name of the league
            
        Returns:
            Optional[Dict]: League data or None if not found
        """
        try:
            league_file = os.path.join(
                self.data_dir, 
                "leagues", 
                f"{league_name.lower().replace(' ', '_')}.json"
            )
            
            if not os.path.exists(league_file):
                logger.error(f"League file not found: {league_file}")
                return None
            
            with open(league_file, 'r', encoding='utf-8') as f:
                return json.load(f)
                
        except Exception as e:
            logger.error(f"❌ Error loading league data: {e}")
            return None
    
    def load_teams_by_league(self, league_name: str) -> List[Team]:
        """
        Load teams for a specific league.
        
        Args:
            league_name (str): Name of the league
            
        Returns:
            List[Team]: List of teams in the league
        """
        try:
            teams_file = os.path.join(
                self.data_dir, 
                "teams", 
                f"{league_name.lower().replace(' ', '_')}_teams.json"
            )
            
            if not os.path.exists(teams_file):
                logger.error(f"Teams file not found: {teams_file}")
                return []
            
            with open(teams_file, 'r', encoding='utf-8') as f:
                teams_data = json.load(f)
            
            teams = []
            for team_name, team_data in teams_data.items():
                teams.append(Team(
                    name=team_data["name"],
                    league=team_data["league"],
                    country=team_data["country"],
                    strength=team_data["strength"],
                    attack=team_data["attack"],
                    defense=team_data["defense"],
                    form=team_data.get("form", 0.0),
                    home_advantage=team_data.get("home_advantage", 0.0),
                    colors=team_data.get("colors", ""),
                    stadium=team_data.get("stadium", ""),
                    capacity=team_data.get("capacity", 0),
                    founded=team_data.get("founded", 1900),
                    nickname=team_data.get("nickname", "")
                ))
            
            logger.info(f"✅ Loaded {len(teams)} teams from {league_name}")
            return teams
            
        except Exception as e:
            logger.error(f"❌ Error loading teams: {e}")
            return []
    
    def get_available_clients(self) -> List[str]:
        """
        Get list of available clients.
        
        Returns:
            List[str]: List of client names
        """
        clients = []
        if not os.path.exists(self.data_dir):
            return clients
        
        for filename in os.listdir(self.data_dir):
            if filename.endswith("_complete.json"):
                client_name = filename.replace("_complete.json", "").replace("_", " ").title()
                clients.append(client_name)
        
        return clients
    
    def get_available_leagues(self) -> List[str]:
        """
        Get list of available leagues.
        
        Returns:
            List[str]: List of league names
        """
        return list(self.leagues.keys())
    
    def get_teams_by_league(self, league_name: str) -> List[Team]:
        """
        Get teams from a specific league.
        
        Args:
            league_name (str): Name of the league
            
        Returns:
            List[Team]: List of teams in the league
        """
        return [team for team in self.teams.values() if team.league == league_name]
    
    def get_team(self, team_name: str) -> Optional[Team]:
        """
        Get a specific team by name.
        
        Args:
            team_name (str): Name of the team
            
        Returns:
            Optional[Team]: Team object or None if not found
        """
        return self.teams.get(team_name)
    
    def get_league_info(self, league_name: str) -> Optional[Dict]:
        """
        Get information about a specific league.
        
        Args:
            league_name (str): Name of the league
            
        Returns:
            Optional[Dict]: League information or None if not found
        """
        return self.leagues.get(league_name)
    
    def export_teams_to_simulation_format(self) -> Dict[str, Any]:
        """
        Export teams in the format expected by the simulation engine.
        
        Returns:
            Dict[str, Any]: Teams in simulation format
        """
        return {
            name: {
                "name": team.name,
                "league": team.league,
                "country": team.country,
                "strength": team.strength,
                "attack": team.attack,
                "defense": team.defense,
                "form": team.form,
                "home_advantage": team.home_advantage
            }
            for name, team in self.teams.items()
        }

def main():
    """Test the data loader functionality."""
    print("🧪 Testing VFL Data Loader")
    print("=" * 30)
    
    loader = DataLoader()
    
    # List available clients
    clients = loader.get_available_clients()
    print(f"📋 Available clients: {clients}")
    
    if clients:
        # Load first available client
        client = clients[0]
        print(f"\n🎯 Loading data for {client}...")
        
        if loader.load_client_data(client):
            print(f"✅ Successfully loaded data for {client}")
            print(f"📊 Leagues: {loader.get_available_leagues()}")
            print(f"👥 Total teams: {len(loader.teams)}")
            
            # Show some sample data
            if loader.teams:
                sample_team = list(loader.teams.values())[0]
                print(f"\n🏆 Sample team: {sample_team.name} ({sample_team.league})")
                print(f"   Strength: {sample_team.strength}, Attack: {sample_team.attack}")
        else:
            print(f"❌ Failed to load data for {client}")
    else:
        print("❌ No client data found. Run generate_data.py first.")

if __name__ == "__main__":
    main()
